### ISSUE TITLE
想錄1個以上的tc要怎麼用比較好

### ISSUE THREAD

**Issue by brina60602** [GiGaFotress/Vtuber-recorder#2]
我是用取得ROOT權限後
cd /home/Vtuber-recorder/
nohup ./index.sh 01 best &
要錄另一個再用另一個設定檔
nohup ./index.sh 02 best &
但有時候其中一個會tc開了卻沒開始錄...

**Comment by GiGaFotress** [comment]
你可以直接用lazyrun，在config里面添加两个txt填入tc地址就行了，index那个是用来录制多平台比较好使的，单平台调用相应的record就行

**Comment by GiGaFotress** [comment]
但是你需要溯源有没有开始录制的话我建议还是先查日志

**Comment by brina60602** [comment]
我在config裡有01.txt  02.txt
今天nohup.out有偵測到01.txt的開播
01/twitcast/log裡也有出現當下錄的日誌

但01/twitcast資料夾裡沒看到01的ts檔
幾分鐘後02開播有正常錄

01的日誌看起來是正常的  最後有出現
video:624773kB audio:106625kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 12.331286%
和5次
@err getStream: 01 --> Offline or User Not Found
就是不知道ts檔到哪去了......
但只錄1個的時候是正常的

**Comment by brina60602** [comment]
我是用lightsail CentOS7

**Comment by GiGaFotress** [comment]
.livedl.log确认有这个的产生并且在正确的目录是吧，01.txt的Savefolder是不是有问题
find 你的录像存储目录/savevideo/ -maxdepth 4    -name "*.ts
找一下看看
